# -*- coding: utf-8 -*-
"""ClaseMS-Numpy_G3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/johnreyes96/modeling-and-simulation/blob/master/scripts/classes/Numpy.ipynb

# Programación y NumPy

En la primera parte de este notebook seguiremos explorando algunas cuestiones de programación. En la segunda parte,
empezaremos a trabajar con NumPy.

## 1. Programación

### 1.1 Operaciones Lógicas

En primer lugar, la operación `not` es simplemente la negación del booleano.
"""
import numpy as np


variable_1 = True
print(not (variable_1))

variable_2 = False
print(not variable_2)

"""La operación `and` nos devuelve `True` unicamente cuando ambas variables son verdaderas. Experimentar con la celda 
inferior y comprobar su tabla de verdad."""

variable_1 = True
variable_2 = True
print(variable_1 and variable_2)

"""**Ejercicio:** comprobar la tabla de verdad de la operación `or` jugando con la celda siguiente."""

A = False
C = False
A_or_B = A or C
print(A_or_B)

"""### 1.2 Estructuras de control - Condicionales

Los condicionales nos permiten ejecutar o no un bloque de codigo dependiendo de ciertas condiciones. En lenguaje 
coloquial, vendrían a ser del estilo de "Si se cumple esta condición, hace A. Si no se cumple, hace B", donde B puede 
ser, simplemente, no hacer nada. Veamos qué formas toman.

### 1.2.1 If

El condicional más simple es el `if`. Para mayor claridad escribiremos la condicion entre parentesis (), aunque esto 
no es necesario. Su estructura es

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
```

Veamos algunos ejemplos:
"""

valor = 15
if (valor > 10):
    print('El valor es mayor que 10')

"""Prestar atención a que la condición debe ser un booleano"""

print(valor > 10)
print(type(valor > 10))

"""**Nota:** para comparar variables, tenemos las operaciones menor `<`, mayor `>`, igualdad `==`, menor o igual  
`<=`, y mayor o igual `>=`."""

print(3 == 3)
print(3 <= 4)
print(3 >= 5)

"""### 1.2.2 If, Else

A la estrucutra con `if` se le puede agregar otro bloque de codigo que se ejecute si la condición exigida NO se 
cumple. Esto se logra mediante la expresión `else`.

``` python
if condicion:
    Si se cumple la condición, se ejecutan estas líneas de código
else:
    Si NO se cumple la condición, se ejecutan estas líneas de código
```
"""

nombre = 'Pedro'

if nombre == 'Juan':
    print('Esta persona se llama Juan')
else:
    print('Esta persona NO se llama Juan')

"""En la condición - lo que está entre paréntesis - es un booleano."""

print('Juan' == 'Pedro')

"""### 1.2.3 If, Elif, Else A esta estructura se le pueden sumar tantas condiciones encadenadas como uno desee, 
mediante la expresión `elif`. El orden en que se van chequeando las condiciones depende de su posición, priemero se 
chequea el `if`, luego el primer `elif`, luego el segundo, y así sucesivamente.

``` python
if condicion_1:
    Si se cumple la condicion_1 , se ejecutan estas líneas de código
elif condicion_2:
    Si se cumple la condicion_2 , se ejecutan estas líneas de código
elif condicion_3:
    Si se cumple la condicion_3 , se ejecutan estas líneas de código
else:
    Si NO se cumple ninguna de las condiciones anteriores, se ejecutan líneas celdas de código
```

"""

edad = 18

if edad < 18:
    print('Esta persona tiene menos de 18 años')
elif edad > 18:
    print('Esta persona tiene mas de 18 años')
else:
    print('Esta persona tiene justo 18 años')

"""**Ejercicio**: Escriba un bloque de código que, dado un número, imprima la frase "El numero es par" si el número 
es par o la frase "El numero es impar" si no lo es."""

numero = 18
# COMPLETAR
if numero % 2 == 0:
    print("El numero es par")
else:
    print("El numero es impar")

"""### 1.3 Combinando estructuras de código

Las estructuras de loops y condicionales se pueden combinar para generar comportamientos más complejos. Supongamos 
que tenemos una lista de edades y nos queremos quedar con aquellas que sean mayores que 18 años. Podemos hacer lo 
siguiente:"""

lista_de_edades = [4, 20, 15, 29, 11, 42, 10, 18]
lista_mayores = []

for edad in lista_de_edades:
    if edad > 18:
        lista_mayores.append(edad)

print(lista_mayores)

"""### 1.4 Operaciones lógicas y estructuras de control

A veces, queremos ejecutar una línea de código si se cumple más de una condición. Esto se puede lograr fácilmente 
usando las operaciones lógicas. Supongamos que tenemos una lista de números, y queremos seleccionar aquellos que 
cumplan ciertas propiedades. Por ejemplo, que son mayores o iguales que 5 y menores que 20. Podríamos hacer lo 
siguiente:"""

numeros = [0, 3, 1, 4, 6, 17, 3, 89, 5, 6, 4, 13, 25, 4, 3, 23, 1, 15, 2]
seleccionados = []
for numero in numeros:
    if numero >= 5:
        if numero < 20:
            seleccionados.append(numero)
print(seleccionados)

"""Notar que los números seleccionados cumplen los requisitos que pedimos. Pero también podríamos hacerlo así:"""

numeros = [0, 3, 1, 4, 6, 17, 3, 89, 5, 6, 4, 13, 25, 4, 3, 23, 1, 15, 2]
seleccionados = []
for numero in numeros:
    if 5 <= numero < 20:
        seleccionados.append(numero)
print(seleccionados)

"""El resultado es el mismo. Si bien esta forma es más compacta, no necesariamente implica que sea mejor. Uno/a elije 
hacerlo de una u otra forma según lo que le parezca más claro; si ambas condiciones juntas son difíciles de leer, 
tal vez puedes usar la primera forma.

**Ejercicio**: Modifica el ejemplo anterior para que seleccione aquellos números **mayores** que 5 **o** impares.
"""

numeros = [0, 3, 1, 4, 6, 17, 3, 89, 5, 6, 4, 13, 25, 4, 3, 23, 1, 15, 2]
seleccionados = []
for numero in numeros:
    if numero > 5 or numero % 2 == 1:
        seleccionados.append(numero)
print(seleccionados)

"""### Repaso

**Ejercicio 1**: ¿Qué pasa si sumás, restás, multiplicás o divides booleanos?
"""

print(True + True + True)
print(True * False)
# COMPLETAR
print(True - False)
print(True / True)

"""**Ejercicio 2**: Hacer una estructur `if/else` que compare dos variables numéricas `A` y `B` y que decida cuál es 
mayor e imprima en pantalla "A es mayor que B" o "B es mayor que A" ."""

A = 3
B = 4
# COMPLETAR
if A > B:
    print("A es mayor que B")
elif A < B:
    print("B es mayor que A")

"""**Ejercicio 3**: Dada la siguiente lista de numeros:"""

numeros = [4, 5, 1, 3, 5, 7, 8, 1, 3, 4, 1, 7, 8, 1, 3, 4, 5, 2, 1, 2, 4, 5]

"""Escribir rutina que calcule la suma de los números **pares menores que 5** en esta lista. **Para tener en cuenta:**
* Hay muchas formas de hacerlo, si piensa en más de una, mejor.
* El resultado es 20.
* Recuerda que puede inicializar una variable en cero, y luego ir modificándola en un loop.
"""

# COMPLETAR
amount = 0
for number in numeros:
    if number < 5 and number % 2 == 0:
        amount = amount + number

print(amount)

"""**Ejercicio 4**: Dada la siguiente lista de numeros:"""

numeros_en_texto = ['2', '3', '2', '3', '2', '2', '2', '2', '3', '2', '3', '1', '3', '1', '2', '2', '2', '2', '2', '2',
                    '2', '2', '1', '2', '3', '2', '2', '2', '2', '1', '2', '3', '2', '2', '3', '2', '3', '3', '2', '2',
                    '1', '3', '3', '2', '3', '2', '2', '1', '2', '1', '1', '2', '2', '3', '2', '2', '2', '3', '2', '2',
                    '2', '1', '2', '2', '3', '2', '2', '2', '2', '1', '2', '2', '2', '2', '3', '1', '2', '3', '3', '2',
                    '3', '2', '2', '3', '3', '1', '1', '3', '2', '1', '2', '2', '2', '1', '1', '2', '2', '2', '2', '2',
                    '2', '2', '3', '3', '1', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '3', '3', '2', '2', '3',
                    '2', '2', '2', '2', '2', '3', '3', '2', '2', '1', '3', '2', '2', '2', '3', '2', '3', '1', '3', '3',
                    '2', '3', '3', '2', '2', '2', '2', '2', '2', '1', '2', '2', '1', '2', '3', '2', '1', '3', '1', '2',
                    '3', '3', '3', '2', '3', '1', '3', '2', '3', '1', '2', '2', '2', '3', '3', '2', '2', '2', '2', '2',
                    '3', '1', '2', '3', '3', '2', '2', '3', '2', '2', '2', '3', '2', '2', '2', '2', '1', '2', '3', '1',
                    '3', '2', '2', '3', '3', '3', '2', '2', '1', '1']
print(numeros_en_texto)

"""Calcule suma de los unos (1) y los tres (3) en esta lista. Hay muchas formas de hacerlo. **Para tener en cuenta:**
* El resultado es 210.

"""

# COMPLETAR
amount = 0
for number in numeros_en_texto:
    if number == '1' or number == '3':
        amount = amount + int(number)

print(amount)

"""## 2. Numpy

Es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran 
volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en 
varias dimensiones, y funciones muy eficientes para su manipulación.

La ventaja de Numpy frente a las listas predefinidas en Python es que el procesamiento de los arrays se realiza mucho 
más rápido (hasta 50 veces más) que las listas, lo cual la hace ideal para el procesamiento de vectores y matrices de 
grandes dimensiones."""

"""Ahora nuestro ambiente de trabajo sabe que si ponemos algo del estilo `np.` significa que esa funcionalidad la 
debe buscar en NumPy.

El principal tipo de dato sobre el que trabaja NumPy son los arreglos o arrays. Los arreglos son parecidos a listas 
y, de hecho, se pueden crear a partir de ellas."""

lista = [0, 1, 2, 3, 4, 5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

"""Pero son más que una lista. Algunas cosas que no se podían hacer con las listas ahora sí se pueden con arreglos. 
Recordemos que sumarle un número a toda la lista no estaba permitido"""

# lista + 1

"""¡Pero ahora con los arreglos sí!"""

arreglo = arreglo + 1

"""Esto simplifica mucho hacer cuéntas. Pero no es sólo sumar, también muchas otras operaciones:"""

print(arreglo - 5)
print(arreglo - 2)
print(arreglo * 4)
print(arreglo ** 2)

"""Comprobar que, salvo la multiplicación, ninguno estaba permitido en listas. ¿Qué hace la multiplicación en el caso 
de una lista?

### 2.1 Creación de arreglos

Si bien podemos crear arreglos a partir de listas, NumPy viene con muchas funciones para hacerlo. Veamos algunas.

Una muy utilizada es `np.arange()`.
"""

np.arange(0, 5, 0.5, dtype=float)

np.arange(0, 5, 0.5, dtype=int)

arreglo = np.arange(3, 20, 2)
print(arreglo)

"""**Ejercicio:** Buscar y crear ejemplos con las siguientes funciones:
* `np.linspace`. Presta particular atención a cómo se diferencia de `np.arange`.
* `np.zeros` y `np.ones`
"""

arreglo = np.linspace(1, 19, 5)
print(arreglo)

arreglo = np.arange(1, 19, 4)
print(arreglo)

"""
### 2.2 Shape de los arreglos

Los arreglos tienen muchos más propiedades que las listas. En particular, pueden tener más de un *eje* o dimensión. 
Veamos a qué nos referimos:"""

arreglo_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arreglo_2d)

"""Notar que tiene dos filas y cuatro columnas. Podemos descubrir esto sin imprimirlo en pantalla, sino usando la 
propiedad `.shape` del arreglo."""

print(arreglo_2d.shape)

"""Primero aparece el número de filas y luego el de columnas. ¿Qué estructura de dato es `(2, 4)`? Otro ejemplo:"""

arreglo_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arreglo_2d)
print(arreglo_2d.shape)

"""Si queremos saber cuántos elementos tiene, podemos usar `.size`"""

print(arreglo_2d.size)

"""### 2.3 Funciones que operan sobre arreglos

Los arreglos de NumPy incorporan un montón de funciones que operan sobre los arreglos. Veamos algunos ejemplos.
"""

un_arreglo = np.array([-100, 2, 3, 17, 25, 1, 95])
print(un_arreglo.min())
print(un_arreglo.max())

"""En el caso 2D, podemos pedir que estas funciones operen sobre todo el arreglo, o por ejes.


"""

arreglo_2d = np.arange(9)
np.random.shuffle(arreglo_2d)
arreglo_2d = arreglo_2d.reshape((3, 3))
print(arreglo_2d)

arreglo_2d = np.arange(9)
print(arreglo_2d)

"""Trata de entender la diferencia entre las siguientes instrucciones:"""

arreglo_2d = np.arange(9)
arreglo_2d = arreglo_2d.reshape((3, 3))
print(arreglo_2d)
print(arreglo_2d.max(axis=0))
print(arreglo_2d.min(axis=1))

"""* No dijimos nada sobre indexado ni slicing. Esto se debe a que, para arreglos 1D, es similar que para la listas. 
Para arreglos 2D, es apenas más complicado. Para estudiarlo, jugar con la siguiente celda:"""

arreglo_2d = np.arange(9).reshape(3, 3)
print(arreglo_2d)
print(arreglo_2d[2, :])

"""* Podemos usar `arreglo.max()` o `np.max(arreglo)`. Esto no es válido solamente para la función `max()`, 
sino también para casi todas las funciones que operen sobre arreglos."""

print(np.min(un_arreglo), un_arreglo.min())

"""### Repaso

**Ejercicio 1**: Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: `linspace`
"""

# COMPLETAR
array = np.linspace(0, 9, 100)
print(array)

"""**Ejercicio 2:** crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos."""

# COMPLETAR
zeros = np.zeros((20,), dtype=int)
for index, number in enumerate(zeros):
    if index < 15:
        zeros[index] = 1

print(zeros)

"""**Ejercicio 3:** crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales 
del 0 al 24."""

# COMPLETAR
zeros = np.zeros((50,), dtype=int)
for index, number in enumerate(zeros):
    if index < 25:
        zeros[index] = index

print(zeros)

"""**Ejercicio 4:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la 
segunda columna por los números 1, 2 y 3 respectivamente. Es decir, crear la siguiente matriz:

```
0 1 0
0 2 0
0 3 0
```
"""

# COMPLETAR
zeros = np.zeros((3, 3), dtype=int)
for index, number in enumerate(zeros):
    zeros[index, 1] = index + 1

print(zeros)

"""**Ejercicio 5:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la 
diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0
0 1 0
0 0 1
```
"""

# COMPLETAR

"""**Ejercicio 6:** crear un arreglo 2D de 100 filas y 100 columnas, lleno de ceros. Reemplazar los elemento de la 
diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 ... 0 0 0
0 1 0 ... 0 0 0
0 0 1 ... 0 0 0
...  
0 0 0 ... 1 0 0
0 0 0 ... 0 1 0
0 0 0 ... 0 0 1
```
"""

# COMPLETAR

"""**Extra:** ¿Qué tipo de dato está usando NumPy cuando crea los arreglos?¿Y si queremos cambiarle el tipo de dato, 
por ejemplo a `int`? Googlear "numpy astype". ¿Qué pasa si usamos `astype(bool)`?"""
